name: 'Test Runner'
description: 'todo'
author: 'Martin Unterhuber'
inputs:
  project-root:
    description: 'Project Root'
    required: true
  script:
    description: 'Script to execute'
    required: true
    default: './gradlew doCustomTest'
  github-token:
    description: 'Github Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: test-runner
        repository: martinunterhuber/test-runner
        fetch-depth: 0
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches-runner
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
      working-directory: ./test-runner
    - uses: nrwl/last-successful-commit-action@v1
      id: last_successful_commit
      with:
        branch: 'master'
        workflow_id: 'build.yml'
        github_token: ${{ inputs.github-token }}
    - name: get diff
      id: diff
      run: |
        DIFF=$(git diff --name-only ${{ steps.last_successful_commit.outputs.commit_hash }} | grep '.*.java')
        echo "::set-output name=diff::$(echo $DIFF | tr '\n' ' ')"
      working-directory: ./main
      shell: bash
    - name: Execute Test Runner
      run: ${{ inputs.script }} --directory=${{ inputs.project-root }} --changed="${{ steps.diff.outputs.diff }}"
      shell: bash
      working-directory: ./test-runner
